### ISSUE TITLE
CDN Cloudfront certificate retrieval

### ISSUE THREAD

**Issue by shashiponnam** [madeindra/setup-guide#11]
Hello Made Indra and other contributors of this guide,

Firstly I appreciate how thoroughly this guide has been documented!

I am currently stuck in the step requiring the AWS CDN cloudfront cert to be added to the whisper.store of android app as instructed in the step 2 of https://github.com/madeindra/setup-guide/tree/master/signal-android

I have spent much time searching online on how to retrieve the AWS CDN cloudfront cert, but could not find an answer. Could you please provide me inputs on how to do that? Maybe this could be added to the FAQ.

Thanks!
Shashi

**Comment by madeindra** [comment]
@shashiponnam  Do you have your cloudfront url?
You can open the url in browser (chrome / firefox), then save the certificate using browser, it's easier.

**Comment by shashiponnam** [comment]
That worked. thank you!
