### ISSUE TITLE
Upload profile image issue

### ISSUE THREAD

**Issue by juvebogdan** [madeindra/setup-guide#12]
Hello,

Updating profile image does not work for me.  I have minio setup and attachments work fine, but I cant upload profile images. What i see in nginx log is the following:

`X.X.X.X - 2ade8f9e-26c8-4189-b20e-456b639cd28c [05/Aug/2020:18:32:13 +0200] "PUT /v1/profile/name/nYosLzuDO08HczPebs%2BNJrU4FN89ifouYSH6IHFIBfCHby2zQqQAxrinsP0itJwTqhjRG3w7 HTTP/1.1" 204 0 "-" "okhttp/3.12.1"
X.X.X.X - 2ade8f9e-26c8-4189-b20e-456b639cd28c [05/Aug/2020:18:32:13 +0200] "GET /v1/profile/form/avatar HTTP/1.1" 200 591 "-" "okhttp/3.12.1"
X.X.X.X - - [05/Aug/2020:18:32:14 +0200] "POST /signalbucket/ HTTP/1.1" 403 314 "-" "okhttp/3.12.1"`

signalbucket is my minio bucket name and it returns 403 for some reason. Same bucket is used for attachments and they work fine.

Only thing that looks weird to me from minio guide is step 8. Inside that code snippet it says domain.com. I changed that to localhost. Is that ok?

Can you help with this?

Thank you

**Comment by madeindra** [comment]
@juvebogdan it's okay to use localhost, as long as it is in format of http://localhost:9000.

403 mean the bucket is not accessible, can you open localhost:9000/signalbucket in your browser?

What is your bucket policy?

**Comment by juvebogdan** [comment]
Thanks for answering. Actually it was my mistake. I created two buckets. One for attachments and one for cdn.

When I used same bucket name for both parts of server conf it worked fine.

**Comment by madeindra** [comment]
Alright, good then if it works, I'm going to close this issue then
