### ISSUE TITLE
Signal server APN service

### ISSUE THREAD

**Issue by tofee91** [madeindra/setup-guide#13]
Hello,

I’m trying to connect my signal server with APNS, but when the iOS client app is terminated I can’t receive the push notification properly and the signal server log this error

```
    WARN [2020-08-07 13:04:05,204] org.whispersystems.textsecuregcm.push.RetryingApnsClient: Got APN failure: DeviceTokenNotForTopic
    WARN [2020-08-07 13:04:05,205] org.whispersystems.textsecuregcm.push.APNSender: *** Got APN generic failure: DeviceTokenNotForTopic, +***************
```
and i can only receive the notification when i open the app.
If the last notification is a voice call, the app will crash when i open it and i have to reopen it again.

I created a development push notification certificate and then i export the certificate and rsa key and set it inside the apn with the bundle id in config file

Thanks

**Comment by madeindra** [comment]
Sorry, I did not see this issue for days since I did not get any notification, unfortunately I can't say a lot about iOS.
But this issue seems to be related iOS in general, not Signal iOS.

https://developer.apple.com/forums/thread/31654
