### ISSUE TITLE
Signal Docker for the new Signal

### ISSUE THREAD

**Issue by SuperCicco** [madeindra/setup-guide#15]
Hello thanks for the guide!

The configuration of the signal-docker for the new version of Signal is the same? Because I have some problems with it.

**Comment by madeindra** [comment]
@SuperCicco It should be the same, but what's the problem? Can you please give me the detail and screenshot, I'll fix the docker.

**Comment by JiriValasek** [comment]
Hi, when using docker, it's necessary to change config.yml to have the right ports 
`accountsDatabase: # database for account`
`  driverClass: org.postgresql.Driver`
`  user:        postgres`
`  password:    postgres`
`  url:         jdbc:postgresql://127.0.0.1:5432/signal`

`messageStore: # database for message`
`  driverClass: org.postgresql.Driver`
`  user:        postgres`
`  password:    postgres`
`  url:         jdbc:postgresql://127.0.0.1:5433/signal`

`abuseDatabase: # database for abuse`
`  driverClass: org.postgresql.Driver`
`  user:        postgres`
`  password:    postgres`
`  url:         jdbc:postgresql://127.0.0.1:5434/signal`

Those ports can be found using `docker-compose ps`.

It might be good to update it in signal-new>config.yml or mention it in the readme...

**Comment by madeindra** [comment]
@JiriValasek Thanks for your feedback, I will update it
