### ISSUE TITLE
How to setup signal-server code without CDS

### ISSUE THREAD

**Issue by aartivshegokar** [madeindra/setup-guide#16]
**I have gone through some pages where CDS setup is given. It is hardware specific (need Intel). Can we setup signal-server without using CDS.**

**Comment by madeindra** [comment]
@aartivshegokar you can follow the guide, the guide is written for those who want to setup signal server without the need of CDS Server

**Comment by aartivshegokar** [comment]
@madeindra Thanks for your quick reply. Can you please share the guide url. I have searched but not able to find it.

**Comment by madeindra** [comment]
@aartivshegokar well, this project is the guide. Look into https://github.com/madeindra/setup-guide/tree/master/signal-server  and you will see that no CDS is involved in the setup

**Comment by swadexi** [comment]
i think the previous version of signal android not use cds, but currently (signal v5) uses /v1/attestation/ that available in cds. or any other solution to solve signal without cds?

**Comment by madeindra** [comment]
@swadexi  I don't see a reason to use signal android v5 while the server code is not even updated beyond v3.21, there's just a lot of gap between them, for me, the only solution is to use the older version.

Also thanks for the question, but please open a discussion thread for any question or discussion instead of commenting on an issue.

**Comment by GitHub-Ram** [comment]
@madeindra shared link : https://github.com/madeindra/signal-setup-guide/tree/master/signal-server is not available.
Please help us eliminating CDS from server as well as app client. Also suggest alternate to discover contact without CDS.

**Comment by mohit-cachy** [comment]
@madeindra Shared links are not working, please help us.
