### ISSUE TITLE
Set up iOS without Contact Directory Service

### ISSUE THREAD

**Issue by iosdevparag** [madeindra/setup-guide#17]
The server has no CDS service and signal - iOS app tries to access --- "v1/attestation/%@ "
it throws 404 has server is without CDS and iOS - Signal throws exception

{ URL: /v1/attestation/823a3b2c037ff0cbe305cc48928cfcc97c9ed4a8ca6d49af6f7d6981fb60a4e9 } { Status Code: 404, Headers {

So we cannot move forward until we skip the attestation or Contact service from client side. 

Guide us to run ios code w/o contact service
Regards,
Parag Deshpande

**Comment by madeindra** [comment]
@iosdevparag first, please tell me what is the version you used for signal server & ios. AFAIK without CDS, there will always be an error, but it's negligible and does not cause any error to the server and client operation, so please also tell me what's making you "cannot move forward"? Is there any crash?

**Comment by iosdevparag** [comment]
> @iosdevparag first, please tell me what is the version you used for signal server & ios. AFAIK without CDS, there will always be an error, but it's negligible and does not cause any error to the server and client operation, so please also tell me what's making you "cannot move forward"? Is there any crash?

Thanks for the reply,  
I am using  ios 3.17.4 server 3.21 , as i mentioned that attestion api fails as we dont have server for that  so owsDebugFails throws exception and i learned i can ignore that. But again i am facing another issue with cdn, It constantly throws  NSURLDOMAIN code -999 cancelled. My CDN url is like   https://xxxxxxxxx.cloudfront.net/   and it  is secured. Also i have added the domain in exceptions of APPTransportSecurtiy in info.plist . Still i am facing the same issue.  Because of this sync contacts api fails and i cannot see any contact to start chat

Can you help me with this.

Regards,
Parag Deshpande

**Comment by madeindra** [comment]
@iosdevparag you sure it's not related to SSL certificate?
Have you followed 6th step on https://github.com/madeindra/setup-guide/tree/master/signal-ios?

**Comment by iosdevparag** [comment]
> @iosdevparag you sure it's not related to SSL certificate?
> Have you followed 6th step on https://github.com/madeindra/setup-guide/tree/master/signal-ios?

Yes we are able to register on server using phone number and getting the otp for verification also. And i have added few contacts in my contact book which are already on server. However iOS client not able to sync contacts and gives error "no signal contacts" so i cannot send or receive messages from them.  
![Simulator Screen Shot - iPhone 11 Pro Max - 2020-10-04 at 00 06 54](https://user-images.githubusercontent.com/71971613/94999288-0b8f1a00-05d6-11eb-94ee-b298dbc98540.png)
![Simulator Screen Shot - iPhone 11 Pro Max - 2020-10-03 at 23 27 18](https://user-images.githubusercontent.com/71971613/94999294-0f22a100-05d6-11eb-884e-45484033b482.png)

What am i missing or is there any thing wrong setup i have done. Can you please guide us.

Regards,
Parag Deshpande

**Comment by madeindra** [comment]
@iosdevparag it usually takes some time for them to show on the list. Can you try "Find Contacts by Phone Number, enter their number, and start chatting.

**Comment by iosdevparag** [comment]
> @iosdevparag it usually takes some time for them to show on the list. Can you try "Find Contacts by Phone Number, enter their number, and start chatting.

I have tried that but not working.  
So as mentioned in your setup guide - step 5 I am not finding such methods and classes in latest code so can you update me with this step and if we dont have cds how will it find that contact in contacts is signal contact on server ?

Regards,
Parag Deshpande

**Comment by madeindra** [comment]
@iosdevparag let me tell you that CDS function is not to synchronizer contact but it's to let other people know others' contact without exposing their ip address, IIRC. So, it's entirely possible not to use CDS in your setup.
