### ISSUE TITLE
fcm (gcm) setup

### ISSUE THREAD

**Issue by JiriValasek** [madeindra/setup-guide#19]
Hi, I am trying to install Signal-Server v3.21 and I am a little bit confused about setting up firebase cloud messaging (It's my first time with it). Could you please clarify what is the API key and Sender ID?

What I did is:
1. I logged into my google account
2. I went to [Google Firebase](https://firebase.google.com/)
3. I clicked `More` and selected `Pricing`
4. In section `Free` I clicked `Start now`
5. I selected `Create a project`
6. I filled in required `Project name`, checked `I accept the Firebase terms`
7. I turned off the `Enable Google Analytics for this project`
8. I clicked `Create project`
9. I went into my project
10. I went into `Project overview > Setting`
11. I switched to `Cloud messaging` tab
Now I see here `Server Key` and `Sender ID` in `Project credentials` section and a `Key pair` which I generated in `Web configuration` section. I also see `Web API Key` on tab `General`.

Am I going right about this and which of these should I use in the `config.yml`

Thanks a lot.

**Comment by madeindra** [comment]
@JiriValasek Server Key is the API Key & Sender ID is below the Server Key
<img width="970" alt="Screen Shot 2020-10-20 at 4 54 11 PM" src="https://user-images.githubusercontent.com/42365530/96570739-e6e4b300-12f4-11eb-8fdc-a2a2fa70c4a1.png">
