### ISSUE TITLE
ZKGROUP_SERVER_PUBLIC_PARAMS value in Signal Android

### ISSUE THREAD

**Issue by tofee91** [madeindra/setup-guide#8]
Hello,
I want to change ZKGROUP_SERVER_PUBLIC_PARAMS value in build.gradle file, but after copying the value that i have generated during signal server installation, it shows the following error "org.signal.zkgroup.InvalidInputException: Length of array supplied was 159 expected 161"
I have tried to padding it with random char but it shows another error "org.signal.zkgroup.InvalidInputException: FFI_RETURN_INPUT_ERROR"

Thanks in advance :)

**Comment by madeindra** [comment]
@tofee91 have you update the dependency in the signal server to zkgroup 0.7.0 then recompiling it?

**Comment by tofee91** [comment]
> @tofee91 have you update the dependency in the signal server to zkgroup 0.7.0 then recompiling it?

@madeindra what is the correct procedure to update it? because i have compiled the signal server and it's working now with updating any dependency

**Comment by madeindra** [comment]
@tofee91 I wrote the new guide, please check it.

It is as simple as changing `0.6.0` to `0.7.0` in the signal-server `pom.xml`

**Comment by tofee91** [comment]
> @tofee91 I wrote the new guide, please check it. https://github.com/madeindra/setup-guide/tree/master/signal-new
> 
> It is as simple as changing `0.6.0` to `0.7.0` in the signal-server `pom.xml`

Thank you, after updating the dependency it works! :)

**Comment by madeindra** [comment]
Alright, I'm gonna close the issue than, thanks for reporting this
